Queued brightness control working with systemd
But this is not a big improvement. Not what I was hoping
for. Certainly not worth the complexity.

diff --git a/bin/omarchy-ddcci-cache b/bin/omarchy-ddcci-cache
--- a/bin/omarchy-ddcci-cache
+++ b/bin/omarchy-ddcci-cache
@@ -1,9 +1,17 @@
 #!/bin/bash
 
 working_dir=/tmp/ddcci
-cache_dir="$HOME/.local/state/ddcci"
+cache_dir=~/.local/state/ddcci
+
+# short circuit if DDC/CI operations are in progress
+if [[ -f "$cache_dir"/pending || $(grep -v '^$' "$cache_dir"/queue | wc -l) != 0 ]]; then
+  echo "Error: DDC/CI operations in progress"
+  exit 1
+fi
 
 # setup
+mkdir -p "$cache_dir"
+touch "$cache_dir"/lock
 rm -rf "$working_dir" > /dev/null 2>&1
 mkdir -p "$working_dir" > /dev/null 2>&1
 cd "$working_dir" > /dev/null 2>&1
@@ -20,18 +28,22 @@ done
 for fn in $(ls -1 display* 2> /dev/null); do
   bus="$(cat "$fn" | awk -F ":" '/I2C bus/ { gsub("/dev/i2c-", ""); print $2 }')"
   brightness="$(ddcutil --bus $bus getvcp 10 | awk '{ gsub(",", ""); print $9 }')"
-  echo "Brightness: $brightness" >> "$fn"
-  echo "Cached at: $(date)" >> "$fn"
+  echo "Current Brightness: $brightness" >> "$fn"
+  echo "Target Brightness: $brightness" >> "$fn"
 done
 
-# clear the old cache files
-rm "$cache_dir/"* > /dev/null 2>&1
-mkdir -p "$cache_dir"
+(flock -x 200
+ # clear the old cache files
+ rm "$cache_dir/"display* > /dev/null 2>&1
+ mkdir -p "$cache_dir"
+ touch "$cache_dir"/lock
+ touch "$cache_dir"/queue
 
-# install the new cache files
-for fn in $(ls -1 display* 2> /dev/null); do
-  mv "$fn" "$cache_dir"
-done
+ # install the new cache files
+ for fn in $(ls -1 display* 2> /dev/null); do
+   mv "$fn" "$cache_dir"
+ done
+) 200>"$cache_dir"/lock
 
 # cleanup
 cd - > /dev/null 2>&1
